# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import io
import base64
import tkinter as tk
from PIL import Image, ImageEnhance


def load_asset(path):
    base = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)


def create_hover_image(img):
    enhancer = ImageEnhance.Brightness(img)
    return enhancer.enhance(1.2)


def create_press_image(img):
    enhancer = ImageEnhance.Brightness(img)
    return enhancer.enhance(0.8)


def pil_to_photoimage(img):
    buffer = io.BytesIO()
    img.save(buffer, format="PNG")
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
    return tk.PhotoImage(data=encoded)


def make_interactive_canvas_image(canvas, x, y, asset_name):
    asset_path = load_asset(asset_name)
    original = Image.open(asset_path)
    normal_image = tk.PhotoImage(file=asset_path)
    hover_image = pil_to_photoimage(create_hover_image(original))
    press_image = pil_to_photoimage(create_press_image(original))

    image_id = canvas.create_image(x, y, image=normal_image)
    image_states = [normal_image, hover_image, press_image]

    canvas.tag_bind(
        image_id,
        "<Enter>",
        lambda event, target=image_id, hover=hover_image: canvas.itemconfig(
            target, image=hover
        ),
    )
    canvas.tag_bind(
        image_id,
        "<Leave>",
        lambda event, target=image_id, normal=normal_image: canvas.itemconfig(
            target, image=normal
        ),
    )
    canvas.tag_bind(
        image_id,
        "<ButtonPress-1>",
        lambda event, target=image_id, press=press_image: canvas.itemconfig(
            target, image=press
        ),
    )
    canvas.tag_bind(
        image_id,
        "<ButtonRelease-1>",
        lambda event, target=image_id, normal=normal_image: canvas.itemconfig(
            target, image=normal
        ),
    )

    return image_id, image_states


window = tk.Tk()
window.geometry("800x600")
window.configure(bg="#000000")
window.title("Untitled")

canvas = tk.Canvas(
    window,
    bg="#000000",
    width=800,
    height=600,
    bd=0,
    highlightthickness=0,
    relief="ridge",
)

canvas.place(x=0, y=0)

image_1 = tk.PhotoImage(file=load_asset("1.png"))

canvas.create_image(400, 300, image=image_1)

image_2 = tk.PhotoImage(file=load_asset("2.png"))

canvas.create_image(400, 300, image=image_2)

image_3 = tk.PhotoImage(file=load_asset("3.png"))

canvas.create_image(400, 302, image=image_3)

image_4_id, image_4_states = make_interactive_canvas_image(canvas, 585, 99, "4.png")

canvas.create_text(
    408,
    84,
    anchor="nw",
    text="Escaneando \npuertos...",
    fill="#ffffff",
    justify="center",
    width=132,
    font=("Inter", 12 * -1),
)

canvas.create_text(
    653,
    84,
    anchor="nw",
    text="No \nSignal",
    fill="#ffffff",
    justify="center",
    width=70,
    font=("Inter", 12 * -1),
)

image_5 = tk.PhotoImage(file=load_asset("5.png"))

canvas.create_image(158, 417, image=image_5)

canvas.create_text(
    625,
    414,
    anchor="nw",
    text="TIEMPO --:--:-- | ΔSINC --ms",
    fill="#ffffff",
    font=("Inter", 6 * -1),
)

image_6 = tk.PhotoImage(file=load_asset("6.png"))

canvas.create_image(399, 482, image=image_6)

image_7_id, image_7_states = make_interactive_canvas_image(canvas, 399, 267, "7.png")

window.resizable(False, False)
window.mainloop()
